<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Gra_w_kości_2026_desktop</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image\kosc0.png" />
    <None Remove="Image\kosc1.png" />
    <None Remove="Image\kosc2.png" />
    <None Remove="Image\kosc3.png" />
    <None Remove="Image\kosc4.png" />
    <None Remove="Image\kosc5.png" />
    <None Remove="Image\kosc6.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Image\kosc0.png" />
    <Resource Include="Image\kosc1.png" />
    <Resource Include="Image\kosc2.png" />
    <Resource Include="Image\kosc3.png" />
    <Resource Include="Image\kosc4.png" />
    <Resource Include="Image\kosc5.png" />
    <Resource Include="Image\kosc6.png" />
  </ItemGroup>

</Project>
